### PR TITLE
Fixes Issue #19

### LINKED ISSUE #19: Update rules in existing security groups
When build-cloud is requested to create security groups, and any of the given security groups are already defined in AWS, I want build-cloud to update the rules in that security group. Current behaviour is to not update the security group.

### PR DESCRIPTION
**Pull request by mikesilky**

### CODE REVIEW

File: lib/build-cloud/securitygroup.rb [hunk 1]
```diff
@@ -80,21 +80,35 @@ def rationalise_rules( authorized_ranges )
         
         security_group.ip_permissions.each do |r|
 
-            c = {
-                :min_port    => r['fromPort'],
-                :max_port    => r['toPort'],
-                :ip_protocol => r['ipProtocol'],
-            }
-
             if r['groups'] != []
```
Comment (madAndroid) [inline lib/build-cloud/securitygroup.rb]: Not your change, and only a stylistic quibble, not an issue...  but may be more legible to use `unless r['groups'].empty?` here

Comment (madAndroid) [inline lib/build-cloud/securitygroup.rb]: Hmm.. on second thought, `if r['groups'] != []` != `unless r['groups'].empty?` - it doesn't take into consideration the possibility of r['groups'] not being set as an array
